name: CI
on:
  push:
    branches: [main, dev, features/*]
    paths-ignore:
      - '.github/workflows/release.yml'
      - 'CHANGELOG.md'
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main, dev]
    paths-ignore:
      - '.github/workflows/release.yml'
      - 'CHANGELOG.md'
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint
      
      - name: Run build
        run: npm run build