name: Production Deployment
description: Deploys the application to Vercel when changes are pushed to the main branch.
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  workflow_run:
    workflows: [CI]
    types: [completed]
    
jobs:
  Deploy-Production:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Notify GitHub deployment start
        uses: bobheadxi/deployments@v1
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: production
      
      - name: Install Vercel Cli
        run: npm install -g vercel@latest
      
      - name: Pull Vercel secrets from github
        run:  vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build project and generate artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
    
      - name: Deploy artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Notify GitHub deployment success
        uses: bobheadxi/deployments@v1
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: success
          env: production