name: Release
on: 
  workflow_dispatch:
jobs:
  release-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Run lint
        run: npm run lint
      - name: Run build
        run: npm run build
  release:
    needs: release-build
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # necessary to reach commit history for tagging and auto generation of release notes by using conventional commits# nécessaire pour push le tag et créer une release
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Initailize git user
        run: |
          git config user.name  "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Run Release
        run: npm run release-i
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}